name: Release TEDI Angular library

on:
  push:
    branches:
      - rc
      - main
    paths-ignore:
      - 'libs/react-components/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
      - name: Navigate to Angular Library module
        run: cd libs/angular-components
      - name: Install dependencies
        run: npm ci --cache .npm --prefer-offline
      - name: Lint
        run: npm run lint:ci

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
      - name: Navigate to Angular Library module
        run: cd libs/angular-components
      - name: Install dependencies
        run: npm ci --cache .npm --prefer-offline
      - name: Test
        run: npm run test

  build-and-deploy:
    needs: [lint, test]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
      - name: Install dependencies
        run: npm ci
      - name: Navigate to Angular Library module
        run: cd libs/angular-components
      - name: Build project
        run: npm run build
      - name: Publish npm package
        run: |
          HUSKY=0
          npm run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPMJS_TEDI_AUTH_TOKEN }}
