name: Test and lint Angular

on:
  pull_request:
    branches:
      - main
      - rc
    paths-ignore:
      - "libs/react-components/**"
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
      - name: Lint
        run: |
          npm ci --cache .npm --prefer-offline
          cd libs/angular-components
          npm ci --cache .npm --prefer-offline
          npm run lint

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
      - name: Test
        run: |
          npm ci --cache .npm --prefer-offline
          cd libs/angular-components
          npm ci --cache .npm --prefer-offline
          npm run test

  chromatic:
    runs-on: ubuntu-latest
    if: github.event.pull_request.head.repo.full_name == github.repository || github.event_name == 'push'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: |
          npm ci --cache .npm --prefer-offline
          cd libs/angular-components
          npm ci --cache .npm --prefer-offline

      - name: Build Storybook
        run: |
          cd libs/angular-components
          npm run build:sb

      - name: Publish to Chromatic
        run: |
          cd libs/angular-components
          CHROMATIC_PROJECT_TOKEN=${{ secrets.CHROMATIC_TOKEN_ANGULAR }} npm run chromatic
